# .github/workflows/nuget-publish-workflow.yml

name: Reusable Build and Publish NuGet Package

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Directory where the library is located'
        required: true
        type: string
      package-source:
        description: 'NuGet source URL for publishing the package'
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        description: 'GitHub token for authentication'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        run: dotnet build --configuration Release
      
      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Pack
        run: dotnet pack --configuration Release --no-restore --output ./nupkg

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./nupkg/*.nupkg --source ${{ inputs.package-source }} --api-key ${{ secrets.GITHUB_TOKEN }}
